#服务器配置
server:
  port: 7700
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: dev
  application:
    name: jc-web
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

### Ribbon 配置
ribbon:
  # 连接超时
  ConnectTimeout: 50000
  # 响应超时
  ReadTimeout: 50000
### Feign 配置
feign:
  # 开启断路器（熔断器）
  hystrix:
    enabled: true

#断路器超时
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #缺省为1000

#注册中心配置
eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    home-page-url-path: /
    #心跳,默认30s
    lease-renewal-interval-in-seconds: 1
    #定义死亡,默认90s
    lease-expiration-duration-in-seconds: 3
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/
    #      defaultZone: http://120.26.50.186:6600/eureka/ #注册远程注册中心
