#Mybatis 打印SQL日志
logging.level.com.jayce.jcweb.common: debug

#开发数据源
spring:
  datasource:
    name: test
    url: @jdbc-url@
    lcn-log-url: @jdbc-url@
    username: @jdbc-user@
    password: @jdbc-password@
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


tx-lcn:
  logger:
    enabled: true
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.lcn-log-url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}