#服务器配置
server:
  port: 7701
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: jc-text
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/library?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#注册中心配置
eureka:
  instance:
    #    statusPageUrlPath: /actuator/info
    #    healthCheckUrlPath: /actuator/health
    #    home-page-url-path: /
    #心跳,默认30s
    lease-renewal-interval-in-seconds: 1
    #心跳,默认30s
    lease-expiration-duration-in-seconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/