#服务器配置
server:
  port: 6666
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: jc-gate
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  cloud:
    client:
      ipAddress: 127.0.0.1
#注册中心配置
eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    home-page-url-path: /
    #心跳,默认30s
    lease-renewal-interval-in-seconds: 1
    #定义死亡,默认90s
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true #以IP地址注册到服务中心
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
    #      defaultZone: http://120.26.50.186:6600/eureka/ #注册远程注册中心

#网关路由配置
zuul:
  ignored-services: "*"
  sensitive-headers:
  prefix: /api #为zuul设置一个公共的前缀
  routes:
    web:
      path: /web/**
      serviceId: jc-web
    text:
      path: /text/**
      serviceId: jc-text
    feign-server:
      path: /feign/**
      serviceId: feign-server

#权限拦截器：配置忽略拦截的请求路径
gate:
  ignore:
    startWith:
      uri: /static,/pms/alipay/callback,/pms/weChatPay/callback,/restaurant/alipay/callback,/restaurant/weChatPay/callback
  user:
    trade:
      time:
        expireSecond: 300
